### ISSUE TITLE
Getting started with Air-light after theme has been generated

### ISSUE THREAD

**Issue by flegfleg** [digitoimistodude/air-light#119]
Hi, i am looking into using air for my development, thanks for the theme! 

I want to make sure that i am not missing something: Is this supposed to be this way?
I understand that air is a "jumping off point" and _not_ a complete theme, but it makes me wonder what else may be broken. 

Thanks!

Examples: 

<img width="805" alt="CleanShot 2021-06-19 at 21 46 24@2x" src="https://user-images.githubusercontent.com/4009931/122653942-77a3b500-d148-11eb-9507-8f2ec35910b6.png">
Menu looks broken

![CleanShot 2021-06-19 at 21 47 09@2x](https://user-images.githubusercontent.com/4009931/122653946-825e4a00-d148-11eb-9b83-dd4562ea0a50.png)
Non-active Menu items are not visible

![CleanShot 2021-06-19 at 21 48 35@2x](https://user-images.githubusercontent.com/4009931/122653948-84280d80-d148-11eb-90f3-7c64f3822701.png)
category page is empty, logo has no contrast.

**Comment by ronilaukkarinen** [comment]
Thank you for the issue. The theme should look like quite empty when it has no ACF or Gutenberg enabled. It should practically look like in the [demo](https://airwptheme.com/demo/) but without hero block (provided by [air-light-demo-content](https://github.com/digitoimistodude/air-light-demo-content) plugin). Archives should look like unstyled as well but you can disable them (and more) by extending functionality with [air-helper](https://github.com/digitoimistodude/air-helper) plugin (or just grab some useful hooks).

Navigation should not be broken and all the spacings etc should work. I'll test the clean installation on Monday to make sure it's fine.

Two questions:
- What way did you use to install Air-light?
- What version of Air-light you are using?

**Comment by flegfleg** [comment]
Hi, thanks for your quick answer! 

I actually tried both 

* forking from github
* downloading from the WordPtess Theme directory

the issues were in both, current version (7.6.6)

**Comment by ronilaukkarinen** [comment]
Thanks for the additional information! I'll test it out soon and let you know what's up. There shouldn't be any bugs but you never know, sometimes human error slips through the releases.

**Comment by ronilaukkarinen** [comment]
When I first activate the theme, it looks like this:

![Screen-Shot-2021-06-21-17-37-59 98](https://user-images.githubusercontent.com/1534150/122780340-704ee980-d2b7-11eb-929e-1c372338e784.png)

This is expected because

* We don't have navigation
* We don't have any content
* We don't have any blocks
* We don't have any CSS of our own 
* etc.

So let me tell you our ways of creating themes.

Please note in here I have created a project with name `cleantest` and theme with textdomain `airclean`.

### 1. Activate ACF

Activate ACF via composer (as explained [here](https://github.com/digitoimistodude/dudestack#advanced-custom-fields-pro)) or manually by zip from [advancedcustomfields.com](https://www.advancedcustomfields.com/):

![Screen-Shot-2021-06-21-17-43-28 66](https://user-images.githubusercontent.com/1534150/122781790-d4be7880-d2b8-11eb-90d4-82e0333e8004.png)


### 2. Create your first content with hero block (CSS + Markup)

We first need to create a block, so let's uncomment these lines and add a hero block (in [functions.php](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/functions.php#L101)):

``` php
    /**
     * Gutenberg -related settings
     */
    // Register custom ACF Blocks
    'acf_blocks' => [
      [
        'name'           => 'hero',
        'title'          => 'Hero',
      ],
    ],
```

Then let's add fields for it (`title`, `content` and select **Show this field group if** _**Block** is equal to **Hero**_:

![Screen-Shot-2021-06-21-17-49-45 43](https://user-images.githubusercontent.com/1534150/122782069-14856000-d2b9-11eb-8e44-688c5c55542f.png)

Create styles for the block in gutenberg/blocks, uncomment [this line](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/sass/gutenberg/_blocks.scss#L33) and add your block like this:

``` scss
  // ACF blocks
  @import 'gutenberg/blocks/hero';
```

Sample gutengerg/blocks/_hero.scss file:

``` scss
.block-hero {
  background-color: var(--color-black);

  .container {
    align-items: center;
    display: flex;

    @media (min-width: $container-mobile) {
      height: 100vh;
      max-height: 60rem;
    }
  }

  .content {
    width: 100%;
  }

  h1,
  p {
    color: var(--color-white);
    margin-left: auto;
    margin-right: auto;
    max-width: 900px;
    text-align: center;
  }
}
```

Run `gulp` or `gulp devstyles` to compile + combine + minify these to global.css.

Add markup for block to template-parts/blocks/hero.php (as indicated [here](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/inc/template-tags/acf-blocks.php#L14):

``` php
<?php
/**
 * Hero block
 *
 * @package airclean
 */

namespace Air_Light;

$title = get_field( 'title' );
$content = get_field( 'content' );

if ( empty( $title ) ) {
  return;
} ?>

<section class="block block-hero has-light-bg">
  <div class="container">

    <div class="content">
      <?php if ( ! empty( $title ) ) : ?>
        <h1 class="block-title"><?php echo esc_html( $title ); ?></h1>
      <?php endif; ?>

      <?php if ( ! empty( $content ) ) : ?>
        <?php echo wp_kses_post( wpautop( $content ) ); ?>
      <?php endif; ?>
    </div>

  </div>
</section>
```

Then we can create Front Page and add the block there:

![Screen-Shot-2021-06-21-18-03-22 57](https://user-images.githubusercontent.com/1534150/122784647-56170a80-d2bb-11eb-9242-b24711871885.png)

And add front page as default home page:

![Screen-Shot-2021-06-21-17-40-22 91](https://user-images.githubusercontent.com/1534150/122784842-7e066e00-d2bb-11eb-8ad3-3d396d9e51cb.png)

### 3. Add navigation

![Screen-Shot-2021-06-21-18-07-24 88](https://user-images.githubusercontent.com/1534150/122784917-8eb6e400-d2bb-11eb-83c9-a49c925d8a23.png)

### 4. Change logo and colors

Let's change the logo for example to [box](https://iconic.app/box/) in [svg/logo.svg](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/svg/logo.svg).

Now let's change the logo size and color by changing/adding these to [_site-header.scss](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/sass/layout/_site-header.scss#L21-L29):

```
  a {
    color: var(--color-white);
  }

  svg {
    height: auto;
    width: 80px;
  }
```

Now it looks like this:

![Screen-Shot-2021-06-21-18-12-11 52](https://user-images.githubusercontent.com/1534150/122785655-38967080-d2bc-11eb-8ab2-5ffabdbfbce4.png)

As you can see current link is too dark for our dark hero so let's just change `--color-current: var(--color-science-blue);` in [_nav-desktop.scss](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/sass/navigation/_nav-desktop.scss#L33) (or alternatively main color from [_colors.scss](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/sass/variables/_colors.scss#L20).

Footer doesn't have any sensible content for this example site I'm building (heh) so let's just disable it for now. Now it looks like this:

![Screen-Shot-2021-06-21-18-15-47 22](https://user-images.githubusercontent.com/1534150/122786196-bbb7c680-d2bc-11eb-95ef-27f7559f7102.png)

Also arrows are too dark so I can change them too. If I don't want nav to be absolute, I can change it to be: `$absolute-navigation: false;` in [_nav-desktop.scss](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/sass/navigation/_nav-desktop.scss#L5)

Then I just need to swap the colors for logo and nav, after that it looks like this:

![Screen-Shot-2021-06-21-18-19-17 58](https://user-images.githubusercontent.com/1534150/122786658-34b71e00-d2bd-11eb-8cfd-5e39730aa1fa.png)

From here I can create more blocks, style more, add more things... you get the picture? This is how we build sites.

### Mobile nav and JS

It seems there's a legit bug in the start scripts because as initting the site there is `navigation.js:106 Uncaught ReferenceError: air_light_screenReaderText is not defined` in navigation.js. This causes JS not to work at all. We need to run `gulp js` once so it compiles all the JavaScript again for our breakpoint in this theme... I'm going to fix this to the next release, thanks for spotting this!

After running `gulp js` task (or just `gulp` with watch) updating nav height to match my "new site" to my height in [_nav-mobile.scss](https://github.com/digitoimistodude/air-light/blob/d9dba961a920df615de01e9b7aa3a94ab37a7dc1/sass/navigation/_nav-mobile.scss#L30) `--height-navigation-mobile: 120px;` the nav is looking and working fine:

![Screen-Shot-2021-06-21-18-25-16 03](https://user-images.githubusercontent.com/1534150/122787479-0be35880-d2be-11eb-88cd-bb8f7c021e6c.png)

### Onboarding / documentation?

I understand we have not documented this part as we presume people know how to do this. The theme is originally built for our company and we onboard our staff to code professional and clean sites with it.

So, maybe some documentation and/or onboarding is needed... we just need to figure out the right way.

So to answer to your original question: Theme is **not** incomplete but you found a bug in start script (gulp not ran in init). We'll fix this.

I hope this quick tutorial helps you getting started! I promise we'll think about the ways we could make getting started with Air-light a bit easier. Currently it is "as is" without much styles, content or onboarding.

**Comment by flegfleg** [comment]
Hi @ronilaukkarinen, thanks very much for your detailed answer! 
From your theme demo i got the impression that the theme to download/clone is in this state, so i wanted to make sure i am not missing anything. I am already using air-light for my next project. 

Thanks again!

**Comment by ronilaukkarinen** [comment]
@flegfleg Awesome! I assume it's safe to close this issue. I will add the tutorial to [wiki](https://github.com/digitoimistodude/air-light/wiki), thanks for the inspiration :) Have fun with Air-light and feel free to leave an issue if you spot one or want to ask more!
