### ISSUE TITLE
Questions about the best approach to convert Adobe XD design into a theme child theming and theme updates

### ISSUE THREAD

**Issue by rahuldhangar** [digitoimistodude/air-light#128]
Dear Team, Thanks for such a wonderful starter theme. I want to know the best approach to convert Adobe XD design into Air-light theme? Should I create a child theme or should I directly make changes to the parent theme? If second option is suggested, then how can I ensure that future updates won't break the theme? Thanks for all your efforts!

**Comment by ronilaukkarinen** [comment]
You're welcome! Glad to have you here.

>  I want to know the best approach to convert Adobe XD design into Air-light theme?

You get the assets from the design, then just start working on it via traditional web programming and [tools](https://github.com/digitoimistodude/awesome-frontend#tools). I usually transform my sites to a working web version by having a Figma (previously XD indeed, my [code editor](https://github.com/ronilaukkarinen/vscode-settings), browser and DevTools all side by side, then using things like [PerfectPixel](https://github.com/digitoimistodude/awesome-frontend#front-end-design-mac-apps) and such to make the front end as polished as possible.

This question is however out of scope of Air-light as it's more a matter of how different front-end coders and agencies do their websites. We at Dude make everyhing as bespoke as possible, from the ground up, without much automatic the layout process with any bloated things like Elementor. We use Air-light + ACF + Gutenberg + our own code instead.

> Should I create a child theme or should I directly make changes to the parent theme?

You have your direct answer in style.css description:

https://github.com/digitoimistodude/air-light/blob/ac185c425a989172d7d2411fe5dc38f632716749/style.css#L6

Here it is as written format:

> I'm a starter theme called <code>Air-light</code>, or <em>air</em>, if you like. I'm a theme based on Automattic's underscores and I'm meant for hacking so **don't use me as a <em>Parent Theme</em>** as-is. Instead try turning me into the next, most awesome, WordPress theme out there. That's what I'm here for. 

So in other words, Air-light is meant to be a starter theme without any parent theme qualities, just like [_s](https://github.com/Automattic/_s) and many themes before it. It has always been this way. This theme is meant to be hacked to pieces and transformed into new beautiful custom themes and websites. You can see sites built on Air-light at the end of [airwptheme.com](https://airwptheme.com/).

>  If second option is suggested, then how can I ensure that future updates won't break the theme?

You should never install Air-light from [theme directory](https://wordpress.org/themes/air-light/) and make minor modifications to it without changing the text domain. This is all explained in the README [here](https://github.com/digitoimistodude/air-light#official-approved-accessibility-ready). Instead, install Air-light properly (you can find installation instructions in the [Wiki](https://github.com/digitoimistodude/air-light/wiki)) by replacing all the textdomains with your own and then built things on top of it.

As for the updates - **you are not supposed to get them**. Your theme will be as-is it was with that current Air-light version. We have some websites with Air-light version 3 or even 2 and they still run just fine despite the fact that the newest version is [7.9.5](https://github.com/digitoimistodude/air-light/releases/tag/7.9.5).

There are couple of reasons for this decicion, let me explain.

1. Air-light is a **dev theme** and it has updates _almost daily_ so it would be impossible to keep up with updates.
2. It is not really necessary anyway, because every site built on Air-light _should be_ different and usually are. For us as a boutique bespoke WordPress agency **every single site is differnent** so those general updates wouldn't affect to them anyway
3. We try to keep the starter theme as minimal as possible so only meaningful "core" things really are: 1) navigation, 2) forms, 3) accessibility. These update rarely because we are aiming to keep the base as complete as possible. If some accessibility things or nav patterns need to be updated on any of our sites based on Air-light, we will just get those code snippets from Air-light to the site. But this happens fairly infrequently, like once in a year - and it's not a big operation. And WHEN things actually would need a bigger refactoring in themes, we then will know the site is from 3 to 10 years old and it will need an upgrade anyway - so we usually get to design a new site from scratch or with the same database and we just pull the newest air and create a new theme for it.

I hope these answer to your questions! Let me know if I can help any other way.
