### ISSUE TITLE
Unable to add blocks

### ISSUE THREAD

**Issue by grandeljay** [digitoimistodude/air-light#131]
Hey

I'm sorry if I misunderstood something here, but shouldn't the add-block button be working here? This is a fresh install of WordPress, there are no plugins installed or anything.

![image](https://user-images.githubusercontent.com/45571053/140885713-7925ba16-e876-4e58-8d08-5df0a06ff00d.png)

**Comment by timiwahalahti** [comment]
Hello @grandeljay!

By default, all WordPress Core blocks are allowed only in posts. This is because we always develop custom blocks to be used on pages for most of the projects.

You may change this behaviour in the functions.php file: https://github.com/digitoimistodude/air-light/blob/master/functions.php#L129-L169

Going to close this issue, but please let me know if you have any further questions!
