### ISSUE TITLE
Has anyone tried integrating tailwind to the theme?

### ISSUE THREAD

**Issue by Zhoha28** [digitoimistodude/air-light#157]
Has anyone tried integrating tailwind to the theme? if so please provide the steps.
I tried following [this issue](https://github.com/digitoimistodude/air-light/issues/130) but still seem to not get anywhere with it.
Thanks in advance!

**Comment by ronilaukkarinen** [comment]
Not that I know of, [as stated](https://github.com/digitoimistodude/air-light/issues/130#issuecomment-1084602886) our team does not use it so we will not include it to our theme. We generally do not offer support for any custom frameworks be it CSS or JS-wise. It makes no sense to write a how-to for each and every single way of doing websites. Air-light is just a ultra-minimal starting point for developers and will be that way.

We always encourage to write your own CSS instead of using ready-made libraries but naturally you are free to do anything you want with air-light.

Tailwind is not very asked feature from Air-light users, in fact you are second to publicly ask about it. So if you get your way with Air-light + Tailwind, please make sure to contribute in form of documentation on how to set up Air-light + Tailwind, that would benefit all the users who prefer Tailwind instead of their own styles.
