### ISSUE TITLE
Remove opinionated colors from the default footer

### ISSUE THREAD

**Issue by simonwimell** [digitoimistodude/air-light#182]
The .site-footer has `color: var(--color-white);` by default, which makes it invisible when setting up a new project. Should the footer either have --color-paragraph as default color, or some background color?

**Comment by ronilaukkarinen** [comment]
There is [no default footer](https://github.com/digitoimistodude/air-light/blob/master/bin/tasks/cleanups.sh#L22-L23). Just build your own footer. This is a starter theme which should not be really anything out of the box before you make it something.

**Comment by simonwimell** [comment]
Following the instructions [here](https://github.com/digitoimistodude/air-light/wiki/Using-with-Local-by-Flywheel-or-other-3rd-party-development-environment) we end up with a footer.

**Comment by simonwimell** [comment]
I mean, it's no real issue for us to work around that in each project, but I don't really understand why we don't get the footer background color that is found on the [wordpress.org theme demo](https://wordpress.org/themes/air-light/) 🤔

**Comment by ronilaukkarinen** [comment]
WordPress theme directory requires a footer and this is why it's included, but our start script with the primary installation method cleans it up, like it should.

Everything you see in the demo is provided by [air-light-demo-content](https://github.com/digitoimistodude/air-light-demo-content) plugin. We don't want to include those in the theme because we then would have to clean up everything manually when starting the project.

In a sense you are correct, the leftovers of the footer should not be there as invisible, but we have seen this as a sign to "do something!". Rather than just wonder why it's we clean it up (or like I said, the script cleans it up for us so we don't see it as white). Air-light is NOT meant to be used as-is without any modifications.

If there is no default, there is no default, and should not be one. Header and navigation are there by default because they are crucial part of the site whereas empty footer is not.

However, we should move these two colors to air-light demo content and remove them from the theme so it would work like this:

![airdev test_](https://user-images.githubusercontent.com/1534150/233623561-ff55527f-c23c-42cf-8d69-955b0540241d.png)

This is a very minor thing to do and lowprio but I'll add it when I have time. Thanks for the input.

**Comment by ronilaukkarinen** [comment]
> I mean, it's no real issue for us to work around that in each project, but I don't really understand why we don't get the footer background color that is found on the [wordpress.org theme demo](https://wordpress.org/themes/air-light/) 🤔

Oh, WordPress adds its own dark overlay in their demo... Didn't notice it earlier. I'll open a separate issue about that preview.

![Screen-Shot-2023-04-21-14-23-09](https://user-images.githubusercontent.com/1534150/233624260-79bfdda5-4e60-4c91-98fa-70ef7b0ab67e.png)

**Comment by simonwimell** [comment]
You're absolutely right, totally low prio :)
