### ISSUE TITLE
No blocks available in page editor

### ISSUE THREAD

**Issue by semidivine** [digitoimistodude/air-light#214]
From the docs I understood that gutenberg blocks were enabled by default. I have none available to me, the page edit screen's "plus" button to add blocks is disabled. Did I miss something in the theme set up? I cannot find any information about this. Thank you!

<img width="1418" alt="Screenshot 2024-03-14 at 2 18 27 PM" src="https://github.com/digitoimistodude/air-light/assets/6435588/d5e7b4cc-4aed-474b-aeba-71e29eb9264b">

**Comment by ronilaukkarinen** [comment]
This is a dev starter theme so there is nothing by default. We do not provide full docs because this is just a starting point. You might want to read [Creating your own Gutenberg blocks with Air light and Advanced Custom Fields](https://github.com/digitoimistodude/air-light/wiki/Creating-your-own-Gutenberg-blocks-with-Air-light-and-Advanced-Custom-Fields) (background: #119).

**Comment by semidivine** [comment]
Actually, I figured it out, it was easy to enable core gutenburg blocks in functions.php. The code was already there. On line 139 I changed this:
```
	 'allowed_blocks' => [
			'default' => [],
```
to this:
```
	 'allowed_blocks' => [
			'default' => [
				'core/gallery',
				'core/image',
				'core/video',
				'core/code',
			],
```
and enabled exactly the blocks I needed.
