### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by filipchrapek** [digitoimistodude/air-light#37]
Hi guys,

I'm playing around with your theme (appreciate it) and here's the question:
whenever I try to add my own filters I get this error:

**Warning: call_user_func_array() expects parameter 1 to be a valid callback**

And I know that the filter is correct, because it is working with other themes. Here I'm trying to wrap post thumbnail in a `<a>` tag.

`add_filter( 'post_thumbnail_html', 'wps_post_thumbnail', 10, 3 );`
 `function wps_post_thumbnail( $html, $post_id, $post_image_id ) {`
  `$html = '<a href="' . get_permalink( $post_id ) . '" title="' . esc_attr( get_post_field( 'post_title', $post_id ) ) . '">' . $html . '</a>';
  return $html;`
`}
`

**Comment by Niq1982** [comment]
Hi Filip,

Theme is now using PHP namespaces. You should define the namespace in the beginning of each file like this: `namespace Air_Light;`. When you need to call the function, you must prefix the call with namespace, for example: `add_filter( 'post_thumbnail_html', __NAMESPACE__ .  '\wps_post_thumbnail', 10, 3 );` (you don't actually need the `wps_` prefix in the function name, since we are using namespaces). 

[Read more about PHP namespaces](https://www.php.net/manual/en/language.namespaces.php)

**Comment by filipchrapek** [comment]
Oh got it, all good now. Appreciate the fast response :)

Cheers!
