### ISSUE TITLE
Future plans, roadmap, etc

### ISSUE THREAD

**Issue by michaelbourne** [digitoimistodude/air-light#44]
Hey everyone,

Just curious what you had in the books for major updates. I'm a fan of Air as a starter theme, but there are a number of ways I alter it with every use. Largely, I use Gutenberg heavily and not ACF, so I add better support for blocks and Gutenberg styles, as well as a new gulp process to make editor styles (so editing a page looks as close as possible to the live view). I also add search capabilities to all sites with a small accessible dialog js library for the search modal. Some other obscure things like prefers-color-scheme support and css variables instead of scss variables. Other css changes..

Mostly curious where your trajectory is taking you with all the new WP changes coming out, with the heavy reliance on Gutenberg, moving to full site editing and reducing the need for the customizer, and the overall goal of making themes be presentation only.

If any of your plans overlap with some of the changes I currently make, I could start sending some PRs your way. I don't want to introduce any breaking changes though since this is your starter theme.

Feel free to email me if you'd prefer to talk about this over email.

**Comment by ronilaukkarinen** [comment]
Hi @michaelbourne! Thank you so much for the comment and contributions this far, glad you like our theme! Currently we use air-light for every project we have (obviously) and I use it also for personal blogs and other WP-related projects (latest air-based is perhaps my personal blog: https://www.rollemaa.fi/). This project also has full Gutenberg support (looks like the same in WP editor, if you are interested in article covering this, [here's one in Finnish](https://www.rollemaa.fi/rollemaan-24-versio-on-taalla-esittelyssa-kasintehty-wordpress-teema/)).

We use Gutenberg in webzines and blogs, because it's easier to handle there. Also we don't want to go too deep in js world or have other depencencies in air-light so that's why Gutenberg is not yet that present. However, we have been planning to do better Gutenberg support and our in-house projects have better defaults.

We don't have a public roadmap, but we do have some stuff on our company todo-list. We discuss air-light related plans and changes bi-weekly. As you can see, some of these are your goals as well:

- Better Gutenberg defaults, for example wider images and captions etc., some blocks we always use should be defaulted
- We do already have separate gulp task for gutenberg.css! This has not yet been implemented to public air-light theme, but we've been planning to do so
- We also do have quite a few versions of search that uses Relevanssi Premium as base, both js and no-js (our searches currently use vue.js, but we've been doing the same with vanilla and mithril.js as well). Because of Relevanssi, we still have not figured out the best way to implement this as default. Some of our searches you can see here: https://www.atena.fi https://www.northpatrol.fi https://www.ctse.fi/ https://www.huurteinen.fi
- Support of CSS variables is in planning as well, we want to make full use of SCSS & CSS features. We won't be giving up SCSS variables though because they are useful in other things like mixins, but will use CSS vars alongside them

So, we're still not sure on many things but will figure it out along the way eventually. The initial goal when we created this theme years back was to honor WordPress core and underscores, to get a WordPress theme with minimal styles and easy starting point. However, after a while we have parted ways with _s style and moved on to PHP namespaces for example. We still will not ever make this like [dustpress](https://github.com/devgeniem/dustpress) or [sage](https://github.com/roots/sage) that would differ entirely from "traditional WordPress" perspective because we want to do things in WPCS way. That being said, we will make some compromises when it comes to usability, coding pleasantness and other things. WordPress structure, templates, etc. we will not touch, we still want to keep them like they are in twenty* and _s while making some slight modifications towards even more minimal approach we are used to.

So, in my opinion you can send the PR and we go it though and see what we can use. How's that sound?

**Comment by ronilaukkarinen** [comment]
@michaelbourne We now have a public roadmap in Favro, feel free to check it out! https://favro.com/organization/3b45e73eaf083f68fefef368/c1dd2d4a99d6723904d2e763

These are the things we are doing anyway and that do not need much of a discussion. If some of these or tasks outside the roadmap need attention, please open an issue here in GitHub and we'll add it as task to the roadmap if worth implementing. 👍

**Comment by ronilaukkarinen** [comment]
As the roadmap is already published and always updating, I'm closing this issue. You can create new issues about feature requests and bugs. 👍
