### ISSUE TITLE
Bulma integration

### ISSUE THREAD

**Issue by Tanmccuin** [digitoimistodude/air-light#47]
Really enjoying Air - though i'm attempting to integrate the Bulma CSS Framework as i've become familiar with it with other projects, but i'm having trouble with the integration, any advice? (attempting via SASS so to be able to affect variables)

**Comment by ronilaukkarinen** [comment]
Glad you are enjoying it! We actually have our own minimal CSS "framework" (to speak) which contains styles for basic elements like forms and typography. We are encouraging people to make their own elements by scratch so the code won't get bloated. As our aim is to keep Air-light as minimal as possible we will not implement any ready-made frameworks like Bootstrap, Foundation, Bulma or even Tailwind as 90% of the code provided by these will not be used or give any advantage.

However if you like to implement Bulma by yourself in your own theme based on Air as I assume your point here, you can of course do it. As Air uses SCSS version of the SASS syntax, default Bulma will not do, because the files are .sass and not .scss. So you'll need to use [scss version of bulma](https://github.com/j1mc/bulma-scss).

As Air includes includepaths by default you can use ANY scss based CSS framework or any other code with it. To use Bulma with Air just run `npm install bulma-scss --save` in your _theme directory_, then add `@include 'bulma-scss/form/input-textarea';` or any other part you want to use or all of them to global.scss. When you compile your scss to css with our gulp tasks you are good to go!
