### ISSUE TITLE
Missing default image

### ISSUE THREAD

**Issue by timiwahalahti** [digitoimistodude/air-light#72]
Since the version 6.5.0 `images` folder seem to have been missing and thus the theme setting `default_featured_image` do not work. We probably should still have some default image in the theme, even we change it in every project.

**Comment by ronilaukkarinen** [comment]
The featured image got left out from styles in the changes after v6 aiming to go towards even more minimalism and less bloat. The idea here is to have default color instead of default image as images are always a hassle to update and extra weight anyway. This made sense when noticed that most of the projects images/ folder contained only default.jpg that was not even used.

I vote for that we have no featured image if there is no image set. It can be set up separately per project and it's the same effort but I rather not keep it by default. Maybe the default.jpg part should be commented out. What do you suggest?

**Comment by timiwahalahti** [comment]
In the case we not having default image bundled, we probably shouldn't have the `default_featured_image` defined in theme settings or at least not used in the hero template part.

I don't have an opinion towards having or not having the default tho, we'll just need to be consistent about in across the theme files.

**Comment by ronilaukkarinen** [comment]
That is true. To be honest, I totally forgot about that function when updating those styles. Can we have best from both worlds and add a check that will not call it at all if there is no file?
