### ISSUE TITLE
git pull new changes to my custom theme

### ISSUE THREAD

**Issue by LukaszJaro** [digitoimistodude/air-light#87]
Looks like many updates are made to this starter theme, even multiple releases in a day! 

If I'm developing my own custom theme using air-light, and want to pull in the latest updates is there a sound process for this? I understand there would eventually be merge conflicts and would have to manually scan through the changes.

**Comment by ronilaukkarinen** [comment]
Hey, great you found us! Good question. Air-light is considered as a dev-theme, it indeed has daily updates and sometimes many releases during the day. Our principle is as a company to not to hold tasks and wait for the right time but to make chances as soon as possible so they will be available in the next project. This way we can iterate the theme best as possible.

This being said, themes based on Air-light are not meant to be updated every time Air-light updates. We have some older sites still up and running with Air version 5.x.x or 4.x.x, maybe even older. Some have gulp v3 whereas the newest air uses gulp v4. Some have been built without webpack and eslint, those came later. Same goes for many many features. It's pure insanity to be able to keep up. Those themes are no longer Air, in fact there's very little of it left since EVERYTHING has been customized for the customer (or for ourselves if it's our personal site in question).

What I mean to say is that Air-light is meant to be hackable in a spirit of all starter themes like this. You sound like you wish Air would be a parent theme and you were able to build your site as a child theme for it to get updates. But this won't be possible since the principle is different. Automattic's underscores puts this well:

"I'm a theme meant for hacking so don't use me as a Parent Theme. Instead try turning me into the next, most awesome, WordPress theme out there."

If you DO want to get updates to your theme based on Air-light, you need to do it manually. We sometimes improve our Air-based sites (we have hundreds of them with different Air versions as base like I said) by taking only those updates we need. For example if the site has jQuery scripts.js in place like it used to be before and we need to get es5 or vue feature we just upgrade gulp and ja base from the latest version. Same goes if we need more up to date SCSS base. We get those pieces manually to the theme. We never update them all, there is no need and it's too much of work.

I hope this clarifies the issue. TL;DR; we don't have a protocol for this and it's intentional choice.
